# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Warrick Corfe-Tan Photography
email: warrickct@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is the photography portfolio and business page for Warrick Corfe-Tan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://warrickctphotography.com" # the base hostname & protocol for your site
twitter_username: warrickct
github_username:  warrickct

# Build settings
markdown: kramdown
